### PR TITLE
Update parser to parse produced output

### LINKED ISSUE #203: URGENT Parsing addendums
We need to parse addendums in any format and get an equivalent result. For example if we parse "NIST SP 800-38A Add. 1" and "NIST.SP.800-38A.add-1" the addedndums should be equivalent, i.e. `id1.addedndum == id2.addendum` should be true.
Currently we have:
```ruby
# Addendem fails to parse
> Pubid::Nist::Identifier.parse "NIST SP 800-38A Add. 1"
Failed to match sequence (OLD_STAGE? (' ' / '.') REPORT_NUMBER PARTS{0, } DRAFT? STAGE? TRANSLATION?) at line 1 char 9.
cause: Failed to match sequence (OLD_STAGE? (' ' / '.') REPORT_NUMBER PARTS{0, } DRAFT? STAGE? TRANSLATION?) at line 1 char 9.
`- Don't know what to do with ". 1" at line 1 char 13.

# The only addedndum I foud that is parsed
> id1 = Pubid::Nist::Identifier.parse "NIST SP 800-38a-add"
#<Pubid::Nist::Identifier:0x000000010a483d60 @publisher=#<Pubid::Nist::Publisher:0x000000010b26c9b8 @publisher="NIST">, @serie=#<Pubid::Nist::Serie:0x000000010b26cc88 @serie="NIST SP", @parsed=nil>, @code="800-38A", @supplement=nil, @update=nil, @addendum="-add">

> id1.addendum
"-add"

# MR addedum with number is parsed without error
> id2 = Pubid::Nist::Identifier.parse "NIST.SP.800-38A.add-1"
#<Pubid::Nist::Identifier:0x000000010a46a298 @publisher=#<Pubid::Nist::Publisher:0x000000010b58ee98 @publisher="NIST">, @serie=#<Pubid::Nist::Serie:0x000000010b58f140 @serie="NIST SP", @parsed=nil>, @code="800-38A", @supplement=nil, @update=nil, @addendum=".add-1">

> id2.addendum
".add-1"

# MR addendum without number is recognized as `translation`
> Pubid::Nist::Identifier.parse "NIST.SP.800-38A.add"
#<Pubid::Nist::Identifier:0x000000010a4812e0 @publisher=#<Pubid::Nist::Publisher:0x000000010b563888 @publisher="NIST">, @serie=#<Pubid::Nist::Serie:0x000000010b563b30 @serie="NIST SP", @parsed=nil>, @code="800-38A", @supplement=nil, @update=nil, @translation="add">
```
We need to parse addedndums with and without numbers. Here is an example of addendum witout number https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a-add.pdf
I suugest that `id.addendum` should be a String and contains just number or empty string if an addendum has no number.

### LINKED ISSUE #204: URGENT Parse MR draft
The we parse pubid it handles draft as a `stage`. It's correct. However, parsing MR handles draft as a `translation`. We need drafts always handled as stages.
```ruby
> pubid = Pubid::Nist::Identifier.parse("NIST SP 800-66r2 IPD")
#<Pubid::Nist::Identifier:0x000000010484a148 @publisher=#<Pubid::Nist::Publisher:0x0000000104c81db0 @publisher="NIST">, @serie=#<Pubid::Nist::Serie:0x0000000104c82f08 @serie="NIST SP", @parsed=nil>, @code="800-66", @stage=#<Pubid::Nist::Stage:0x0000000104c81950 @id="i", @type="pd">, @supplement=nil, @update=nil, @revision="2">

> pubid.stage
#<Pubid::Nist::Stage:0x0000000104c81950 @id="i", @type="pd">

> pubid.translation
nil

> pubid.to_s :mr
"NIST.SP.800-66r2.ipd"

> pubid = Pubid::Nist::Identifier.parse("NIST.SP.800-66r2.ipd")
#<Pubid::Nist::Identifier:0x0000000104823200 @publisher=#<Pubid::Nist::Publisher:0x0000000105b24908 @publisher="NIST">, @serie=#<Pubid::Nist::Serie:0x0000000105b24bb0 @serie="NIST SP", @parsed=nil>, @code="800-66", @supplement=nil, @update=nil, @revision="2", @translation="ipd">

> pubid.stage
nil

> pubid.translation
"ipd"
```

### LINKED ISSUE #206: Add tests that make sure we can parse output we produce
related #203 #202

### PR DESCRIPTION
**Pull request by mico**
closes #206 
closes #203 
closes #204

### CODE REVIEW

**Review by ronaldtse — APPROVED** [review]
@andrew2net this looks reasonable, please let @mico know if it's sufficient. Thanks!

**Review by andrew2net — COMMENTED** [review]
It still does not parse produced output
```ruby
> id = Pubid::Nist::Identifier.parse('NIST.SP.800-121r2')
=> #<Pubid::Nist::Identifier:0x000000010a595f00
 @code="800-121",
 @publisher=#<Pubid::Nist::Publisher:0x0000000109f7d118 @publisher="NIST">,
 @revision="2",
 @serie=#<Pubid::Nist::Serie:0x0000000109f7d708 @parsed=nil, @serie="NIST SP">,
 @supplement=nil,
 @update=nil>

> id.update = Pubid::Nist::Update.new number: 1
=> #<Pubid::Nist::Update:0x000000010a73ddd0 @number=1, @year=nil>

> id.to_s
=> "NIST SP 800-121r2/Upd1"

> id.to_s :mr
=> "NIST.SP.800-121r2.u1"

> Pubid::Nist::Identifier.parse "NIST SP 800-121r2/Upd1"
Pubid::Core::Errors::ParseError: Failed to match sequence (OLD_STAGE? (' ' / '.') REPORT_NUMBER PARTS{0, } DRAFT? STAGE? TRANSLATION?) at line 1 char 11.
...
```

**Comment by mico** [comment]
> ```ruby
> NIST SP 800-121r2/Upd1
> ```

@andrew2net This was fixed in https://github.com/metanorma/pubid-nist/pull/210

**Comment by andrew2net** [comment]
@mico
In the `Pubid::Nist::Addendum` class can we delegate methods `code`, `publisher`, `series` etc, to `@base` variable? Or just call all missing methods on `@base` object. So we don't have to check every time  if a pubid is a `Addedndum` or has the `base` method. These if else conditions will pollute the relaton code badly.
And rename the `Pubid::Nist::Addendum@number` to something `Pubid::Nist::Addendum@add_number` to distinguish it from possible other `number`s.

**Comment by mico** [comment]
> @mico
> In the `Pubid::Nist::Addendum` class can we delegate methods `code`, `publisher`, `series` etc, to `@base` variable? Or just call all missing methods on `@base` object. So we don't have to check every time if a pubid is a `Addedndum` or has the `base` method. These if else conditions will pollute the relaton code badly.
> And rename the `Pubid::Nist::Addendum@number` to something `Pubid::Nist::Addendum@add_number` to distinguish it from possible other `number`s.

@andrew2net I don't think it's a good solution, for many other "pubid" gems we do it the same way. But maybe we're missing something that can make life easier. Could explain in more details what are you trying to do so we can find a better solution?
@ronaldtse any thoughts?

**Review by andrew2net — APPROVED** [review]

**Review by andrew2net — CHANGES_REQUESTED** [review]
#204 is still persist.
```ruby
Pubid::Nist::Identifier.parse("NIST SP 800-66r2 ipd").stage
=> #<Pubid::Nist::Stage:0x000000010e090038 @id="i", @type="pd">

Pubid::Nist::Identifier.parse("NIST SP 800-66r2 ipd").to_s :mr
=> "NIST.SP.800-66r2.ipd"

Pubid::Nist::Identifier.parse("NIST.SP.800-66r2.ipd").stage
=> nil

Pubid::Nist::Identifier.parse("NIST.SP.800-66r2.ipd").translation
=> "ipd"
```

**Review by andrew2net — CHANGES_REQUESTED** [review]
#203 doesn't work as expected
```ruby
id1 = Pubid::Nist::Identifier.parse("NIST SP 800-38A-add")
=> #<Pubid::Nist::Identifier:0x00000001098e6d68
 @addendum="-add",
 @code="800-38A",
 @publisher=#<Pubid::Nist::Publisher:0x000000010daa54e8 @publisher="NIST">,
 @serie=#<Pubid::Nist::Serie:0x000000010daa5790 @parsed=nil, @serie="NIST SP">,
 @supplement=nil,
 @update=nil>

id1.to_s
=> "NIST SP 800-38A Add."

id2 = Pubid::Nist::Identifier.parse "NIST SP 800-38A Add."
Pubid::Core::Errors::ParseError: Failed to match sequence (OLD_STAGE? (' ' / '.') REPORT_NUMBER PARTS{0, } DRAFT? STAGE? TRANSLATION?) at line 1 char 9.
cause: Failed to match sequence (OLD_STAGE? (' ' / '.') REPORT_NUMBER PARTS{0, } DRAFT? STAGE? TRANSLATION?) at line 1 char 9.
`- Don't know what to do with "." at line 1 char 13.

from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/pubid-core-1.10.3/lib/pubid/core/identifier/base.rb:154:in `rescue in parse'
Caused by Parslet::ParseFailed: Failed to match sequence (OLD_STAGE? (' ' / '.') REPORT_NUMBER PARTS{0, } DRAFT? STAGE? TRANSLATION?) at line 1 char 9.
from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/parslet-2.0.0/lib/parslet/cause.rb:70:in `raise'

id2 = Pubid::Nist::Identifier.parse "NIST SP 800-38A Add"
=> #<Pubid::Nist::Identifier:0x000000010c435280
 @code="800-38A",
 @publisher=#<Pubid::Nist::Publisher:0x000000010e235de8 @publisher="NIST">,
 @serie=#<Pubid::Nist::Serie:0x000000010e236090 @parsed=nil, @serie="NIST SP">,
 @supplement=nil,
 @translation="Add",
 @update=nil>

id1 == id2
=> false
```

**Comment by andrew2net** [comment]
@mico sorry, I used GH version of pubid-core, everything works now.

**Review by andrew2net — APPROVED** [review]

**Pull request merged**
