### PR TITLE
Bad PubID generation for CSRC Whitepaper + Update series long descriptions and rename "serie" to "series"

### LINKED ISSUE #217: Bad PubID generation for CSRC Whitepaper
From @opoudjis https://github.com/metanorma/metanorma-nist/issues/392#issuecomment-1878653619

````
{:number=>"January 15, 2019", :serie=>"CSRC White Paper", :edition_year=>"2013", 
:edition_month=>"01", :edition_day=>"01", :stage=> Pubid::Nist::Stage.new(:id=>nil, :type=>"pd")}
````

(FYI @opoudjis )
This example is now *invalid* because CSRC White Papers have been retroactively assigned sequential IDs now, see:
* https://www.relaton.org/blog/2023-08-22-nist-cswp-pubid/

This means we should not cram a date string inside `number:`.

It should now be:
````
{:number=>"999", :serie=>"CSWP", :edition_year=>"2013", 
:edition_month=>"01", :edition_day=>"01", :stage=> Pubid::Nist::Stage.new(:id=>'i', :type=>"pd")}
````

* Short:
  * Before: NIST CSRC White Paper 999 (IPD) (January 01, 2013)
  * Now: NIST CSRC White Paper 999e20130101 pd
  * Should be: NIST CSWP 999e20130101 ipd

* Long:
   * Before: NIST Cybersecurity White Paper 999 (IPD) (January 01, 2013)
   * After: National Institute of Standards and Technology Cybersecurity Resource Center White Paper  Public Draft 999 Edition 20130101
   * Should be: National Institute of Standards and Technology Cybersecurity White Paper 999 (Initial Public Draft) (January 01, 2013)

* Machine-Readable:
  * Before: NIST.CSWP.IPD.January 15, 2019.eng
  * After:  NIST.CSWP.January 15, 2019e20130101.pd
  * Before: NIST.CSWP.999e20130101.ipd

_Originally posted by @opoudjis in https://github.com/metanorma/metanorma-nist/issues/392#issuecomment-1878653619_

### LINKED ISSUE #218: Update "CSRC White Paper" to "CSWP" series abbreviation
According to https://www.nist.gov/system/files/documents/2022/04/01/PubID_Syntax_NIST_TechPubs.pdf
“CSRC White Paper” not in use anymore, new identifiers using “CSWP”.

related #217

### LINKED ISSUE #220: Rename "serie" parameter to "series"
> And instead of the hash parameter being `serie`, it should just be `series`, see:
Screenshot 2024-02-06 at 4 11 45 PM

_Originally posted by @ronaldtse in https://github.com/metanorma/pubid-nist/issues/217#issuecomment-1928982787_

### PR DESCRIPTION
**Pull request by mico**
closes #218 
closes #217 
closes #220 
related #222

### CODE REVIEW

**Comment by opoudjis** [comment]
The changes look reasonable, let me test against my data and update the ticket information that this originated from.

**Review by opoudjis — CHANGES_REQUESTED** [review]
Improved, but there are still issues in the examples in https://github.com/metanorma/metanorma-nist/issues/392, including your updates: "( Third)" instead  of "(Third Edition)", for example. Please check all examples there carefully.

**Comment by ronaldtse** [comment]
Ping @mico for fixes.

**Comment by mico** [comment]
@opoudjis @ronaldtse the aim of this pull request is only to fix #217
I had no intention here of fixing anything else from https://github.com/metanorma/metanorma-nist/issues/392

**Pull request merged**
